version: '3.8'

networks:
  z43_network:
    driver: bridge

services:
  python_server:
    container_name: python_server
    image: python:latest
    volumes:
      - ./py/server.py:/server.py
    command: python -u /server.py 0.0.0.0 8000
    networks:
      - z43_network

  python_client:
    container_name: python_client
    image: python:latest
    volumes:
      - ./py/client.py:/client.py
    command: python /client.py python_server 8000
    networks:
      - z43_network
    depends_on:
      - python_server
      - c_server

  c_server:
    container_name: c_server
    build: ./c/server/
    command: ./c_server 8001
    networks:
      - z43_network

  c_client:
    container_name: c_client
    build: ./c/client/
    command: ./c_client c_server 8001
    networks:
      - z43_network
    depends_on:
      - c_server
      - python_server
