version: '3.8'

networks:
  z43_network:
    driver: bridge

services:
  python_server:
    container_name: python_server
    image: python:latest
    volumes:
      - ./py/server.py:/server.py
    command: python /server.py
    ports:
      - 8000:8000
    expose:
      - 8000
    networks:
      - z43_network

  python_client:
    container_name: python_client
    image: python:latest
    volumes:
      - ./py/client.py:/client.py
    command: python /client.py
    networks:
      - z43_network
    depends_on:
      - python_server
