version: '3.8'

networks:
  default:
    name: z43_network
    external: true

services:
  z43_server_python_parallel:
    container_name: z43_server_python_parallel
    image: python:3
    volumes:
      - ./py/server.py:/server.py
    command: python -u /server.py 0.0.0.0 8000

  z43_client_c:
    container_name: z43_client_c
    build: ./c/client/
    command: ./c_client z43_server_python 8000
    depends_on:
      - z43_server_python_parallel
